language: python
node_js:
  - "7"
before_install:
  - node -v
  - npm -v
install:
  - node -v
  - npm -v
  - chmod +x ./ci/install-ng.sh
  - chmod +x ./ci/install-django.sh 
script:
  - node -v
  - npm -v
