# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloHerramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Herramienta')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Insumo')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Protocolo')),
            ],
        ),
    ]
